name: Locale
on: [push]

jobs:
  build:
    name: Setup Locale variables for Linux environment (included Streamlit)
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: SetLocale
      run: |
        sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen pt_BR.UTF-8
        sudo localectl set-locale LANG="pt_BR.UTF-8"
        export LANG="pt_BR.UTF-8"
        sudo update-locale
